version: 2.0
jobs:
  build:
    docker:
    - image: golang:1.9
    working_directory: /go/src/github.com/gliderlabs/com
    steps:
    - checkout
    - run: go get ./...
    - run: go test -v -race ./...
